#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ if/end data.values.swarmSettings.enabled:
---
apiVersion: v1
kind: Secret
metadata:
  name: bee-swarm-secret
  namespace: #@ data.values.namespace
type: Opaque
stringData:
  #@yaml/text-templated-strings
  swarmKeys: |-
    (@= yaml.encode(data.values.swarmSettings.swarmKeys)@)

