#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ if/end data.values.libp2pSettings.enabled:
---
apiVersion: v1
kind: Secret
metadata:
  name: bee-libp2p-secret
  namespace: #@ data.values.namespace
type: Opaque
stringData:
  #@yaml/text-templated-strings
  libp2pKeys: |-
    (@= yaml.encode(data.values.libp2pSettings.libp2pKeys)@)
