#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")

#@ if/end data.values.clefSettings.enabled:
---
apiVersion: v1
kind: Secret
metadata:
  name: bee-clefpassword-secret
  namespace: #@ data.values.namespace
type: Opaque
data:
    password: #@ base64.encode(data.values.clefSettings.password)
