#@ load("@ytt:data", "data")

#@ if/end data.values.serviceAccount.create:
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: #@ data.values.serviceAccount.name
  namespace: #@ data.values.namespace