#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ if/end data.values.clefSettings.enabled:
---
apiVersion: v1
kind: Secret
metadata:
  name: bee-clef-secret
  namespace: #@ data.values.namespace
type: Opaque
stringData:
  #@yaml/text-templated-strings
  clefKeys: |-
    (@= yaml.encode(data.values.clefSettings.clefKeys)@)
