#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Service
metadata:
  labels:
    endpoint: p2p
  name: bee-public
  namespace: #@ data.values.namespace
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 30675
      port: 1634
      protocol: TCP
      targetPort: 1634
  selector:
    app: bee
  sessionAffinity: None
  type: LoadBalancer
