#@ load("@ytt:data", "data")

#@ if data.values.serviceAccount.create:
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: #@ data.values.serviceAccount.name
  namespace: #@ data.values.namespace

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-services
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-services
  namespace: #@ data.values.namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read-services
subjects:
  - kind: ServiceAccount
    name: #@ data.values.serviceAccount.name
    namespace: #@ data.values.namespace

#@ end