#@data/values-schema
---
beeConfig:
  #! allow to advertise private CIDRs to the public network
  allow_private_cidrs: false
  #! HTTP API listen address
  api_addr: :1633
  #! Chain block-time
  block_time: 15
  #! Initial nodes to connect to
  bootnode: [ "" ]
  #! Cause the node to always accept incoming connections
  bootnode_mode: false
  #! Enable clef signer
  clef_signer_enable: true
  #! Set clef signer endpoint
  clef_signer_endpoint: http://localhost:8550
  #! Origins with CORS headers enabled
  cors_allowed_origins: ""
  #! Data directory
  data_dir: /home/bee/.bee
  #! DB capacity in chunks
  cache_capacity: 1000000
  #! Number of open files allowed by database
  db_open_files_limit: 200
  #! Size of block cache of the database in bytes
  db_block_cache_capacity: 33554432
  #! Size of the database write buffer in bytes
  db_write_buffer_size: 33554432
  #! Disables db compactions triggered by seeks
  db_disable_seeks_compaction: false
  #! Debug HTTP API listen address
  debug_api_addr: :1635
  #! Enable debug HTTP API
  debug_api_enable: true
  #! Set the run mode - light by default
  full_node: true
  #! Disable a set of sensitive features in the api
  gateway_mode: false
  #! Enable global pinning
  global_pinning_enable: false
  #! Enable mainnet
  mainnet: false
  #! NAT exposed address
  nat_addr: ""
  #! Password for decrypting keys (please change it for production deployments)
  #! If not set, it will be automatically generated
  #! required to be provided
  password: ''
  #! Path to a file that contains password for decrypting keys is /home/bee/.secret/password
  usePasswordFile: false
  #! percentage below the peers payment threshold when we initiate settlement
  payment_early_percent: 50
  #! Threshold in BZZ where you expect to get paid from your peers
  payment_threshold: 100000000
  #! excess debt above payment threshold in percentages where you disconnect from your peer
  payment_tolerance_percent: 25
  #! Postage stamp address
  postage_stamp_address: ""
  #! Price oracle address
  price_oracle_address: ""
  #! P2P listen address
  p2p_addr: :1634
  #! Enable P2P QUIC transport
  p2p_quic_enable: false
  #! Enable P2P WebSocket transport
  p2p_ws_enable: false
  #! Whether node starts with no listen addresses for p2p
  standalone: false
  #! Static overlay addresses to protect on bootnode
  static_nodes: ""
  #! ID of the Swarm network
  network_id: 10
  #! Enable SWAP
  swap_enable: true
  #! Set swap ethereum blockchain endpoint
  swap_endpoint: ""
  #! Set swap factory address
  swap_factory_address: ""
  #! Set swap legacy factory addresses
  swap_legacy_factory_addresses: ""
  #! Set gas price in wei to use for deployment and funding
  swap_deployment_gas_price: ""
  #! Set initial deposit if deploying a new chequebook
  swap_initial_deposit: 10000000000000000
  #! Resolver connection string
  resolver_options: ""
  #! Enable tracing
  tracing_enable: false
  #! Endpoint to send tracing data
  tracing_endpoint: 127.0.0.1:6831
  #! Service name identifier for tracing
  tracing_service_name: bee
  #! Proof-of-identity transaction hash
  #@schema/type any=True
  transaction: null
  #! Log verbosity level 0=silent, 1=error, 2=warn, 3=info, 4=debug, 5=trace
  verbosity: 5
  #! Send a welcome message string during handshakes
  welcome_message: "Welcome to the Swarm, you are Bee-ing connected!"